### ISSUE TITLE
Unable to locate process after hot-code swap

### ISSUE THREAD

**Issue by szlend** [bitwalker/swarm#10]
I have a GenServer that I register using the `{:via, ...}` tuple. After running a hot code upgrade my process isn't reachable anymore. I wonder if it has something to do with topology change. Maybe Swarm is trying to route it to the wrong node? But either way I think it might be a good idea to add the upgrader node to the blacklist. Or is the name too general?

```
iex(testapp@testapp-node-01.lan)4> pid = Swarm.whereis_name(:foo)
#PID<0.1304.0>
iex(testapp@testapp-node-01.lan)5> Process.alive? pid
true

22:43:11.968 [info] [swarm on testapp@testapp-node-01.lan] [tracker:nodeup] nodeup testapp_upgrader_9310@testapp-node-01.lan
22:43:11.973 [info] [swarm on testapp@testapp-node-01.lan] [tracker:topology_change] topology change complete
22:43:13.023 [info] [swarm on testapp@testapp-node-01.lan] [tracker:nodedown] nodedown testapp_upgrader_9310@testapp-node-01.lan
22:43:13.023 [info] [swarm on testapp@testapp-node-01.lan] [tracker:topology_change] topology change complete

iex(testapp@testapp-node-01.lan)7> Process.alive? pid
true
iex(testapp@testapp-node-01.lan)8> pid = Swarm.whereis_name(:foo)
:undefined
```

**Comment by szlend** [comment]
Yeah, I just whitelisted all my nodes and that fixed the problem. Still, processes registered with the `:via` tuple cannot be relocated so they probably shouldn't be affected by topology changes, right?

**Comment by bitwalker** [comment]
Yeah there is definitely a bug in the topology change handler, I'll take a look. FYI, if you run `:sys.trace(Swarm.Tracker)` it will dump a lot more debug info if you have your log level set to debug. Helps when tracing these issues :)

**Comment by szlend** [comment]
Ah, that's good to know, thanks :)

**Comment by bitwalker** [comment]
@szlend Quick question, were you able to reliably reproduce this every time, or did it appear to occur randomly? If you didn't try multiple times that's cool, figure I would ask before I dig in too deep, I have some ideas about what may have caused it.

**Comment by szlend** [comment]
Yeah, I could I reproduce it reliably. Though I only tried it a couple of times.

**Comment by bitwalker** [comment]
Ok cool, I'll be looking at it this afternoon, so hopefully I'll have an update soon.

**Comment by bitwalker** [comment]
Just an update, I was able to reproduce the problem, and I'm working on a fix (there are actually a couple of fixes, but I found them due to how I was testing things when trying to reproduce). I'm doing some clean up around how the state machine stuff is handled in order to accommodate the fix, so it will be sometime tomorrow probably before I can get it wrapped up.

**Comment by bitwalker** [comment]
@szlend Mind giving 3.0 or master a shot? There have been several fixes made, and I believe this issue should be resolved now.

**Comment by szlend** [comment]
@bitwalker It only works if the upgrade node is blacklisted, which it is by default since 2.0.2. Otherwise the issue is still there.

```
11:12:12.100 [info]  [swarm on testapp@127.0.0.1] [tracker:init] started
11:12:17.101 [info]  [swarm on testapp@127.0.0.1] [tracker:cluster_wait] joining cluster..
11:12:17.101 [info]  [swarm on testapp@127.0.0.1] [tracker:cluster_wait] no connected nodes, proceeding without sync
11:12:17.102 [debug] [swarm on testapp@127.0.0.1] [tracker:handle_call] registering #PID<0.574.0> as :worker, with metadata %{}

** Upgrade **

11:13:12.496 [warn]  [swarm on testapp@127.0.0.1] [tracker:nodeup] nodeup for testapp_maint_17205@127.0.0.1 was ignored because swarm failed to start: {:badrpc, :nodedown}
11:13:12.880 [info]  [swarm on testapp@127.0.0.1] [tracker:nodeup] nodeup testapp_upgrader_17165@127.0.0.1
11:13:12.881 [debug] [swarm on testapp@127.0.0.1] [tracker:handle_topology_change] topology change (nodeup for testapp_upgrader_17165@127.0.0.1)
11:13:12.881 [debug] [swarm on testapp@127.0.0.1] [tracker:handle_topology_change] removing registration for :worker, testapp@127.0.0.1 is down
11:13:12.882 [info]  [swarm on testapp@127.0.0.1] [tracker:handle_topology_change] topology change complete
11:13:13.311 [info]  [swarm on testapp@127.0.0.1] [tracker:nodedown] nodedown testapp_upgrader_17165@127.0.0.1
11:13:13.311 [debug] [swarm on testapp@127.0.0.1] [tracker:handle_topology_change] topology change (nodedown for testapp_upgrader_17165@127.0.0.1)
11:13:13.311 [info]  [swarm on testapp@127.0.0.1] [tracker:handle_topology_change] topology change complete
```

It removes the registration for some reason:
```
removing registration for :worker, testapp@127.0.0.1 is down
```

I'm not sure why it does that, maybe it's trying to hand it off to the other node? Though that shouldn't happen with processes registered with the `:via` tuple right?

**Comment by bitwalker** [comment]
Looks to me like the node monitor for the testapp node is being triggered by the upgrade, but I'll have to test, it's definitely not a handoff as that would be present in the logs

**Comment by daya** [comment]
any progress on this issue?
